### ISSUE TITLE
Using aioisotp concurrently with udsoncan Client

### ISSUE THREAD

**Issue by dpatel20** [christiansandberg/aioisotp#4]
Not sure this is the correct place to ask but what I am trying to do is run aioisotp in order to send data but also to listen any CAN messages for the given rxid on the same channel, such that I could use udsoncan client in parallel (the client has some nice built in functionality such as handling NRCs, checking the response, etc that I'd like to make use of).

So, what I thought of was:

```python
async def infinite(rdr):
    while True:
        payload = await rdr.read(4095)
        print(payload)

async def main():
    network = aioisotp.ISOTPNetwork(0,
                                    interface='vector',
                                    receive_own_messages=False, tx_padding=0x0)
    with network.open():
        reader, writer = await network.open_connection(0x7BB, 0x7B3)
        asyncio.create_task(infinite(reader))
```

I then send something using the udsoncan client and was hoping the aioisotp reader would also grab it (for logging purposes). But it does not get it...

In general, I would use the ```writer``` to send 'raw' data and then ```reader``` would get the data. But at times I would like to use the functionality of udsoncan client but still have the ability to grab the received uds message using the ```reader```and log it.

I must admit I am new to StreamReader/Writer so not sure how they work exactly. However, if I create 3 connections - one of which is functional address and send functionally, the other 2 connections will get their respective responses.

Is there any way to get the reader to listen for anything on the bus that matches the given rxid?

**Comment by dpatel20** [comment]
As an afterthought, if it was listening to stuff triggered by something else, I guess aioisotp would try to do flow control, etc which may cause issues. So, I guess I'm looking for a 'listen/spy' mode...is that possible?

**Comment by dpatel20** [comment]
OK, this is a little weird...it seems to work sometimes but other times it seems the ```on_message_received``` is not triggered. I can't see why it would work sometimes but not others...

I am using a different app altogether (commercial)  to send some uds requests - sometimes ```on_message_received``` fires, sometimes not.

I used the python-can notifier and can see all the uds frames there...so, at that level, they are receiving them.

**Comment by dpatel20** [comment]
I have figured out the issue...my fault...using ```with network.open():``` and then that was timing out meaning the listener was stopping. Added an ```await asyncio.sleep(60)``` in the ```with``` and all is good for 60s. Need to understand now how best to fix it.

**Comment by christiansandberg** [comment]
Yes, as you say I think the main problem here is that there is nothing keeping the application alive. You probably want some loop or blocking call in the main thread. Maybe `await infinite(reader)` in your example.

I should warn you that I will probably not keep developing this anymore. A better solution is to make [python-can-isotp](https://github.com/pylessard/python-can-isotp) asyncio friendlier and wrap that instead. But it requires some redesign to make it work. Since I'm not working with ISO-TP anymore I don't have much incentive to put in the hours unfortunately.
