### ISSUE TITLE
Sometimes receive 2 messages together

### ISSUE THREAD

**Issue by dpatel20** [christiansandberg/aioisotp#5]
Occasionally, if 2 messages are received on the bus close together, I find that when using this library the messages can come back as combined.
For example, 
03 7F 36 78 00 00 00 00   
02 76 02 00 00 00 00 00   
I receive these 2 messages <2ms apart (as shown in CANalyzer).

aioisotp returns it as one combined message: 7f36787602 (have put debug print in `on_message_received()` of `ISOTPNetwork` to confirm it is combined there). I don't see the same issue using python-can-isotp.

I know this library is not maintained but I was hoping you might be able to give me an insight into why this might happen so I can take a look further. I am using asyncio and would prefer to continue using this library if possible.

I am on Windows using Vector HW.

**Comment by dpatel20** [comment]
I noticed that in `StreamReader` protocol it was extending the buffer within `feed_data`:

```python
self._buffer.extend(data)
```
And changing that to:
```python
self._buffer=bytearray(data) 
```
means it now works. But I am sure that is not the correct thing to do. I really don't know much about this side of asyncio but perhaps there is a way to achieve the same thing through 'proper' means? i.e. have `StreamReader` process only one message at a time?

I presume the issue is that the `reader.read()` has not occurred before the second piece of data comes in. And, so, when the `read()` does occur the buffer now has 2 messages in it. I had thought that the `_wakeup_waiter()` in `feed_data()` would handle this - i.e. wakeup the `read()` function such that one message is read.

**Comment by christiansandberg** [comment]
I think this is how StreamReader is supposed to work. It abstracts the framing of the underlying protocol, providing a single byte stream. It is the same as a standard socket connection.

**Comment by christiansandberg** [comment]
What protocol are you using? Is it two single frames? I only thought about request/response type of protocols like UDS when I designed this so then it is usually not possible for two responses to occur simultaneously.

**Comment by dpatel20** [comment]
This is UDS and, yes, 2 single frames arriving from the ECU in close proximity. The issue case is the ECU is sending NRC78 (response pending) and then almost immediately following up with the final response.

After a bit of digging into the StreamReader code, I put a [question over on SO](https://stackoverflow.com/questions/71007653/ensure-streamreader-handles-one-message-at-a-time) of what I think is happening in StreamReader.

I agree it's probably how StreamReader is supposed to work but wondered if there was a 'correct' way of handling it.

**Comment by christiansandberg** [comment]
It was a long time ago I used UDS and ISO-TP so I don't remember the details. It could just be the case that my assumption that an ISO-TP frame can be combined without the knowledge of the protocol is wrong.
