### ISSUE TITLE
Bump python-can version

### ISSUE THREAD

**Issue by belliriccardo** [christiansandberg/aioisotp#6]
Right now when the package is installed it will revert the current `python-can` installation from the latest version (4.3.1 at the time of writing, release date Dec 12 2023) with version 3.3.4, with release date Oct 4 2020; this release in particular is tagged with "[Last planned release with Python2 support! 🎆](https://github.com/hardbyte/python-can/releases/tag/3.3.4)". Since a quick check with [vermin](https://github.com/netromdk/vermin) proves that python 2 is incompatible with this package anyways and  since the python-can library improved quite a lot since then shouldn't the transition be natural and easy?

For more context, I stumbled here from the package `udsoncan`, which in some cases requires it; when I tried installing this package, it reverted the `python-can` installation by almost four years, causing some problems. Hope this doesn't cause too many headaches!

**Comment by christiansandberg** [comment]
This project is pretty much archived, I haven't got around to archiving it properly in GitHub yet.

But you are welcome to submit a pull request to update it and I will accept.

**Comment by belliriccardo** [comment]
@christiansandberg I figured something was up, seeing the history of the commits! I've made some modifications to my program and I'm now using another library for isotp; if I come back to this and make some changes I'll make sure to share them! Closing the issue
